export interface Video {
  id: string;
  title: string;
  channelName: string;
  channelImage: string;
  thumbnailUrl: string;
  videoUrl: string;
}

export const videos: Video[] = [
  {
    id: "1",
    title: "React Tutorial for Beginners",
    channelName: "Coding Academy",
    channelImage: "https://picsum.photos/seed/react/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/Ke90Tje7VS0/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Ke90Tje7VS0",
  },
  {
    id: "2",
    title: "TypeScript Crash Course",
    channelName: "Dev Insights",
    channelImage: "https://picsum.photos/seed/typescript/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/BCg4U1FzODs/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/BCg4U1FzODs",
  },
  {
    id: "3",
    title: "Tailwind CSS: From Zero to Hero",
    channelName: "CSS Wizards",
    channelImage: "https://picsum.photos/seed/tailwind/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/UBOj6rqRUME/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/UBOj6rqRUME",
  },
  {
    id: "4",
    title: "Next.js 13 Crash Course",
    channelName: "Web Dev Simplified",
    channelImage: "https://picsum.photos/seed/nextjs/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/Y6KDk5iyrYE/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Y6KDk5iyrYE",
  },
  {
    id: "5",
    title: "GraphQL Basics - Build an API from Scratch",
    channelName: "Backend Mastery",
    channelImage: "https://picsum.photos/seed/graphql/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/YyUWW04HwKY/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/YyUWW04HwKY",
  },
  {
    id: "6",
    title: "Docker for Beginners: Full Course",
    channelName: "DevOps Decoded",
    channelImage: "https://picsum.photos/seed/docker/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/fqMOX6JJhGo/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/fqMOX6JJhGo",
  },
  {
    id: "7",
    title:"Ekko & Jinx/Powder (Arcane) | Ma meilleure ennemie - Stromae & Pomme",
    channelName: "Kate Johnson",
    channelImage: "https://picsum.photos/seed/netflix/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/orxCH7LzJ9c/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/orxCH7LzJ9c",
  },
  {
    id: "8",
    title: "Isha makes the ultimate sacrifice to save Jinx",
    channelName: "Still Watching Netflix",
    channelImage: "https://picsum.photos/seed/prime/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/ZVTDEZvFU6k/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/ZVTDEZvFU6k",
  },
  {
    id: "9",
    title: "Ayyan - Earthquake (Official Audio)",
    channelName: "Ayyan",
    channelImage: "https://picsum.photos/seed/ayyan/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/A4kuZiWiios/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/A4kuZiWiios",
  },
  {
    id: "10",
    title: "Chendumallika Poo - Video Song 1080p HD",
    channelName: "Arya 2",
    channelImage: "https://picsum.photos/seed/arya/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/WrCc7E-GE9E/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/WrCc7E-GE9E",
  },
  {
    id: "11",
    title: "Morni | Badshah | Sharvi Yadav | Preity Mukhundhan | Hiten",
    channelName: "Saregama Music",
    channelImage: "https://picsum.photos/seed/morini/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/Zrt77f7nTqY/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Zrt77f7nTqY",
  },
  {
    id: "12",
    title: "KL 42 Lyrics • GABRI • prod. KEVIN SONEY • KaruppRecords",
    channelName: "OldPill",
    channelImage: "https://picsum.photos/seed/oldpill/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/3TfDIOiuWvc/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/3TfDIOiuWvc",
  },
  {
    id: "13",
    title: "FARZI || Paisa Hai Toh",
    channelName: "Farzi",
    channelImage: "https://picsum.photos/seed/farzi/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/d_W42XNvYSY/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/d_W42XNvYSY",
  },
  {
    id: "14",
    title: "Kanninathan Kamanottam | Devara",
    channelName: "T-Series Malayalam",
    channelImage: "https://picsum.photos/seed/devara/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/Do1c7Eyrr38/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Do1c7Eyrr38",
  },
  {
    id: "15",
    title: "Colt & Jody - I Was Made for Lovin' You | The Fall Guy",
    channelName: "Fall Guy",
    channelImage: "https://picsum.photos/seed/fallguy/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/35VDphr95dw/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/35VDphr95dw",
  },
  {
    id: "16",
    title: "Kakkothikkavile Video song | Chathickatha Chandu",
    channelName: "T-Series",
    channelImage: "https://picsum.photos/seed/moon/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/p4vUFUFVy5E/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/p4vUFUFVy5E",
  },
  {
    id: "17",
    title: "Rise Of Dragon",
    channelName: "Think Music India",
    channelImage: "https://picsum.photos/seed/dragon/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/XRJbfvhS6T0/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/XRJbfvhS6T0",
  },
  {
    id: "18",
    title: "Leo - Ordinary Person Video ",
    channelName: "SonyMusicSouthVEVO",
    channelImage: "https://picsum.photos/seed/sonymusic/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/q6e_b0NERCA/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/q6e_b0NERCA",
  },
  {
    id: "19",
    title: "Linkin Park - Roads Untraveled - Need for Speed",
    channelName: "Niche Films",
    channelImage: "https://picsum.photos/seed/untravelled/50/50",
    thumbnailUrl: "https://img.youtube.com/vi/8UoMY6oN1tg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/8UoMY6oN1tg",
  },
];
